//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2eksamnen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ansatte
    {
        public int Medarbejderid { get; set; }
        public string Navn { get; set; }
        public int Telefonnr { get; set; }
        public decimal Løn { get; set; }
        public string Jobtype { get; set; }
        public short Dommerlevel { get; set; }
    }
}
