//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2eksamnen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spillere
    {
        public int SpillerId { get; set; }
        public string Navn { get; set; }
        public string In_game_name { get; set; }
        public Nullable<int> Rank { get; set; }
        public int Telefonnummer { get; set; }
        public string Turneringstype { get; set; }
    }
}
