//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2eksamnen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turneringer
    {
        public int Turneringsid { get; set; }
        public string Turneringsnavn { get; set; }
        public int SpillerID { get; set; }
        public string Spillernavn { get; set; }
        public int Telefonnummer { get; set; }
        public int DommerID { get; set; }
        public string Dommernavn { get; set; }
        public int Dommertelefon { get; set; }
        public int Dommerlevel { get; set; }
    }
}
